import { css } from '../../../../styled-system/css';

export const markdownContentStyles = css({
  '& h1': {
    fontSize: { base: '2xl', sm: '3xl' },
    fontWeight: 'bold',
    mt: '8',
    mb: '6',
    pb: '2',
    borderBottom: '1px solid',
    borderColor: 'border.default',
    color: 'text.default',
  },
  '& h2': {
    fontSize: { base: 'xl', sm: '2xl' },
    fontWeight: 'bold',
    mt: '8',
    mb: '5',
    color: 'text.default',
  },
  '& h3': {
    fontSize: { base: 'lg', sm: 'xl' },
    fontWeight: 'bold',
    mt: '6',
    mb: '4',
    color: 'text.default',
  },
  '& p': {
    mb: '5',
    lineHeight: 'relaxed',
    fontSize: { base: 'base', sm: 'lg' },
    color: 'text.muted',
    textWrap: 'pretty',
  },
  '& ul': { listStyleType: 'disc', pl: '5', mb: '5', color: 'text.muted' },
  '& ol': { listStyleType: 'decimal', pl: '5', mb: '5', color: 'text.muted' },
  '& li': { mb: '2' },
  '& a': {
    color: 'link.default',
    textDecoration: 'underline',
    _hover: { color: 'link.hover' },
  },
  '& code': {
    fontFamily: 'mono',
    bg: 'bg.subtle',
    color: 'accent.default',
    px: '1.5',
    py: '0.5',
    borderRadius: 'sm',
    fontSize: '0.9em',
    fontWeight: 'medium',
  },
  '& [data-rehype-pretty-code-figure]': {
    my: '8',
    '& [data-rehype-pretty-code-title]': {
      bg: 'bg.muted',
      color: 'text.muted',
      fontSize: 'xs',
      fontFamily: 'mono',
      px: '4',
      py: '2',
      borderTopRadius: 'md',
      borderX: '1px solid',
      borderTop: '1px solid',
      borderColor: 'border.muted',
    },
    '& pre': {
      bg: 'bg.muted',
      p: '4',
      borderRadius: 'md',
      overflowX: 'auto',
      border: '1px solid',
      borderColor: 'border.muted',
      fontSize: 'sm',
      lineHeight: 'relaxed',
      '&[data-has-title]': {
        borderTopRadius: 'none',
      },
    },
    '& code': {
      bg: 'transparent',
      p: 0,
      color: 'inherit',
      fontSize: 'inherit',
      fontWeight: 'inherit',
      display: 'grid',
    },
    '& [data-highlighted-line]': {
      bg: 'overlay.light',
      borderLeft: '2px solid',
      borderColor: 'accent.default',
      mx: '-4',
      px: '4',
    },
  },
  '& blockquote': {
    borderLeft: '4px solid',
    borderColor: 'border.default',
    pl: '4',
    py: '1',
    fontStyle: 'italic',
    color: 'text.muted',
    my: '6',
  },
  '& table': {
    w: 'full',
    borderCollapse: 'collapse',
    mb: '8',
    display: 'block',
    overflowX: 'auto',
  },
  '& th': {
    borderBottom: '2px solid',
    borderColor: 'border.default',
    px: '4',
    py: '3',
    textAlign: 'left',
    fontWeight: 'bold',
    color: 'text.default',
  },
  '& td': {
    borderBottom: '1px solid',
    borderColor: 'border.muted',
    px: '4',
    py: '3',
    color: 'text.muted',
  },
});
